hello/urls.py
from django.urls import path

from hello import views

urlpatterns = [
    path('', views.index, name='index'),
    path('fancy-hello', views.fancy_index, name='fancy_index'),
    path('<str:name>', views.hello_name, name='hello_name'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("todolist/", include("todolist.urls")),
    path("admin/", admin.site.urls),
    path("", include("hello.urls")),
]

todolist/urls.py
from django.urls import path

from todolist import views


app_name = 'todolist'
urlpatterns = [
    path('', views.index, name='tasks_list'),
    path('add/', views.add, name='add_task')
]

hello/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models

# Create your models here.

todolist/forms.py
from django import forms


class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task')
    priority = forms.IntegerField(min_value=1, max_value=10)

hello/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return HttpResponse('<h1 style="color:green;">Hello from the first app</h1>')


def fancy_index(request):
    return render(request, "hello/index.html")


def hello_name(request, name):
    data = {
        'name': name.capitalize(),
        'time': datetime.datetime.now(),
        'show_time': True
    }
    return render(request, "hello/greet.html", data)

todolist/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from todolist.forms import NewTaskForm


def index(request):
    return render(request, 'todolist/index.html', {'todolist': request.session.get('tasks', [])})


def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            if 'tasks' not in request.session:
                request.session['tasks'] = []
            request.session['tasks'].append(task)
            return HttpResponseRedirect(reverse('todolist:tasks_list'))
        else:
            return render(request, 'todolist/add.html', {'form': form})
    return render(request, 'todolist/add.html', {'form': NewTaskForm()})

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    Hello, from the first app
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/hello/style.css' %}" >
</head>
<body>
    <h1 class="title">Hello, guys!</h1>
</body>
</html>

todolist/templates/todolist/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDoList App</title>
</head>
<body>
<h3>Add Task</h3>
<form action="{% url 'todolist:add_task' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'todolist:tasks_list' %}">View task list</a>
</body>
</html>

todolist/templates/todolist/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDoList App</title>
</head>
<body>
<h3>Tasks:</h3>
<ul>
    {% for item in todolist %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>
<a href="{% url 'todolist:add_task' %}">Add new task</a>
</body>
</html>